### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/dx-measure#1]
### High-level features

- [x] Choose a tool 
- [ ] Measure a tool 
- [ ] Share on social media
- [x] Display leaderboard on landing page

### API roadmap 

- [x] Integrate API endpoints with data storage
- [x] Require user to be authenticated to measure APIs 
- [ ] Apply rate limit to the creation of rates per tool
- [ ] Perform security/performance reviews

### UI roadmap 
- [ ] Responsive for mobile 
- [ ] Extract repetitive UI chunks into separate components
- [ ] Test performance on different browsers/devices 

### Misc
- [ ] Buy domain (update all references to Vercel domain, eg: OAuth GitHub app, Supabase redirect URLs)
- [ ] Update READMEs
- [ ] Update on my portfolio CMS
- [ ] Share on social media
